### ISSUE TITLE
I have try the basic setup in react-formal with react-formal-inputs I have an error

### ISSUE THREAD

**Issue by ghost** [jquense/react-formal-inputs#5]
this is the error : 

 [React Widgets] You are attempting to use a widget that requires localization (Calendar, DateTimePicker, NumberPicker). However there is no localizer set. Please configure a localizer. 

I'm currently looking for a solution and update you if you want

**Comment by jquense** [comment]
since this adapter uses `react-widgets` you need to follow the getting started instructions for them. 

http://jquense.github.io/react-widgets/docs/#/?_k=24sb08
